### ISSUE TITLE
Robot Movement is Choppy

### ISSUE THREAD

**Issue by a-ehlinger** [anubiscapstone/pcbase#11]
Especially the arm movement, the servos seems to move in a very choppy manner rather than smoothly.  The cause still needs to be determined, as I don't believe this issue was present last year.

**Comment by anubiscapstone** [comment]
The movement hasn't been as choppy in a long time, but it will now seem to freeze for a moment every second or so.  This has been observed in SkeletonViewer's drawing as well.  The issues could be related and possibly a performance bottleneck with stuff being delegated on the same thread.

**Comment by a-ehlinger** [comment]
This could potentially be a race condition with the internal SkeletonRep in KinectInterface.  It is defaulted before all of its tracked values are set.  The modifySkeleton method may be accessing it during this time.
