### ISSUE TITLE
Problems with Gestures

### ISSUE THREAD

**Issue by anubiscapstone** [anubiscapstone/pcbase#2]
We need to resolve the following problems with gestures:
 - we don't understand how they work
 - robot moves without operator walking
 -

**Comment by TSmithONU** [comment]
Person to contact for that would be Noah orr.

**Comment by Drew-Newman** [comment]
Or me for tread movements. I did some of that code.

**Comment by a-ehlinger** [comment]
It seems that we had some issues with the batteries dying on us.  This was causing odd behavior where limbs would stop responding or the treads would move without input.
