### ISSUE TITLE
Clean up repo of stuff that doesn't need tracked.

### ISSUE THREAD

**Issue by a-ehlinger** [anubiscapstone/pcbase#3]
Basically set up the .gitignore files.  Things like build outputs, binaries, logs, etc. don't need to be and shouldn't be tracked because they make commits harder to read and make sense of.  Having them caught by a git status also makes staging things and checking diffs a pain.

**Comment by anubiscapstone** [comment]
Most of the build stuff from the PCBase code should be untracked and ignored now.  If more comes up, it can be tacked on to other commits.

**Comment by anubiscapstone** [comment]
closed via 24c39ef016c51bc50a85cf04d506fa87e6070aa9

**Comment by anubiscapstone** [comment]
closed via 494ccc149403d6b9b5f6d01d92e770ba1fbd383f
closed via 4a2fb16231b40981e1f8fed843c359f97c2f0850
