### ISSUE TITLE
The battery pack on the robot and its on/off button are hard to reach

### ISSUE THREAD

**Issue by a-ehlinger** [anubiscapstone/pcbase#7]
We need to come up with a better solution for powering the beaglebone and the wifi adapter.  The current solution is not easily accessible without unscrewing things.  Turning the robot on/off should be as simple as an easily accessible button press or switch.

**Comment by cbarber101** [comment]
http://www.amazon.com/Poweradd-Charging-Portable-Identification-Smartphones/dp/B00MWU1GGI/ref=sr_1_1?ie=UTF8&qid=1458095049&sr=8-1&keywords=poweradd+slim2
Now have 4 of these which are better situated on the robot. They also turn on when a USB device is connected.
